### PR TITLE
Removing Expo dependencies, add polygons vectors

### PR DESCRIPTION
**Pull request by gutoglup**
This change has fixed the issues cited: #55, #51

They were implemented as following features:
- Removal of the **Expo** dependency, so that the code does not require the Expo library to be required.
- Implementation of **vector layers**, allowing the tracing of polygons in the map.

Following is the sample code for executing the property to draw polygons:
```javascript 
geometryLayers={[
  {
    id: 1,
    coords: [[51.515, -0.09], [51.52, -0.1], [51.52, -0.12]],
    color: '#123123',
    },
  ]}
```

This is the image of the implementation.
Captura de Tela 2019-08-08 às 15 07 41

### CODE REVIEW

**Comment by reggie3** [comment]
Thanks for the contribution @gutoglup

**Comment by hussainahmad** [comment]
@reggie3  could you please release the new version with the latest changes.

**Comment by tifus69** [comment]
Please how to get the latest version ? I have the 5.0.2 and still issues with expo...

**Comment by reggie3** [comment]
What kind of issues are you having?

**Comment by tiagofppereira** [comment]
`error: bundling failed: Error: Unable to resolve module `@unimodules/core` from `node_modules/expo-file-system/build/FileSystem.js`: @unimodules/core could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
    at ModuleResolver.resolveDependency (/Users/tiagopereira/PhpStormProjects/soscovidapp/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:186:15)
    at ResolutionRequest.resolveDependency (/Users/tiagopereira/PhpStormProjects/soscovidapp/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/tiagopereira/PhpStormProjects/soscovidapp/node_modules/metro/src/node-haste/DependencyGraph.js:282:16)
    at Object.resolve (/Users/tiagopereira/PhpStormProjects/soscovidapp/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at /Users/tiagopereira/PhpStormProjects/soscovidapp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:426:31
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/tiagopereira/PhpStormProjects/soscovidapp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:423:18)
    at /Users/tiagopereira/PhpStormProjects/soscovidapp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/tiagopereira/PhpStormProjects/soscovidapp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)`



I'm having this error, still with expo depedencies?

**Comment by tiagofppereira** [comment]
`error: bundling failed: Error: Unable to resolve module `@unimodules/core` from `node_modules/expo-file-system/build/FileSystem.js`: @unimodules/core could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
    at ModuleResolver.resolveDependency (/Users/tiagopereira/PhpStormProjects/<name_of_app>/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:186:15)
    at ResolutionRequest.resolveDependency (/Users/tiagopereira/PhpStormProjects/<name_of_app>/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/tiagopereira/PhpStormProjects/<name_of_app>/node_modules/metro/src/node-haste/DependencyGraph.js:282:16)
    at Object.resolve (/Users/tiagopereira/PhpStormProjects/<name_of_app>/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at /Users/tiagopereira/PhpStormProjects/<name_of_app>/node_modules/metro/src/DeltaBundler/traverseDependencies.js:426:31
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/tiagopereira/PhpStormProjects/<name_of_app>/node_modules/metro/src/DeltaBundler/traverseDependencies.js:423:18)
    at /Users/tiagopereira/PhpStormProjects/<name_of_app>/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/tiagopereira/PhpStormProjects/<name_of_app>/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)`

Still having this error

**Comment by asamiz** [comment]
@tiagofppereira I am facing the same issue, did you find any solution for this?

**Pull request merged**
